
PROJECT_ROOT=$(pwd)
SRC=$PROJECT_ROOT/src
DIST=$PROJECT_ROOT/dist

NODE_MODULES=$PROJECT_ROOT/node_modules
NODE_BIN=$NODE_MODULES/.bin

PATH=$NODE_BIN:$PATH

DOCS_FILE=$PROJECT_ROOT/README.md
NPMIGNORE=$PROJECT_ROOT/.npmignore
PACKAGE_JSON=$PROJECT_ROOT/package.json
LICENSE=$PROJECT_ROOT/LICENSE

cp $DOCS_FILE $DIST
cp $NPMIGNORE $DIST
cp $PACKAGE_JSON $DIST
cp $LICENSE $DIST
